---

- name: add the webapp user's home dir
  file: dest={{ webapps_home }} mode=755 state=directory

- name: add limited user for webapps
  user: name={{ webapp_user }} comment="I run webapps" system=yes home={{ webapps_home }}

- name: chown the webapp user's home dir
  file: dest={{ webapps_home }} owner={{ webapp_user }} group={{ webapp_user }}
